/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ouc.cpss.view;


import com.ouc.cpss.biz.CustomerBiz;
import com.ouc.cpss.biz.CustomerBizImpl;
import com.ouc.cpss.po.Customer;
import com.ouc.cpss.util.LocationUtil;
import com.ouc.cpss.util.StringUtil;
import java.math.BigDecimal;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * 客户管理界面
 * @author su
 */
public class CustomerFrame extends javax.swing.JInternalFrame {

    CustomerBiz cusbiz = new CustomerBizImpl();
    /**
     * Creates new form CustomerFrame
     */
    public CustomerFrame() {
        initComponents();
        //初始化保存按钮
        this.btnSave.setEnabled(false);
        this.btnDelete.setEnabled(false);
        //显示在中间
        LocationUtil.setScreenCenter(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        basicPicPane1 = new com.ouc.cpss.view.BasicPicPane();
        txtCondition = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCustomer = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCusid = new javax.swing.JTextField();
        txtCusname = new javax.swing.JTextField();
        txtTbid = new javax.swing.JTextField();
        txtCustel = new javax.swing.JTextField();
        txtCuszip = new javax.swing.JTextField();
        txtCusaddr = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnLoad = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("买家管理");

        basicPicPane1.setPreferredSize(new java.awt.Dimension(809, 500));

        btnSearch.setText("搜索");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        tblCustomer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "买家编号", "姓名", "淘宝昵称", "联系电话", "邮编", "送货地址"
            }
        ));
        tblCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCustomerMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCustomer);

        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("编号");

        jLabel2.setText("联系电话");

        jLabel3.setText("送货地址");

        jLabel4.setText("姓名");

        jLabel5.setText("邮编");

        jLabel6.setText("淘宝昵称");

        txtCusid.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCustel, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                            .addComponent(txtCusid))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCuszip, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtCusname, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtTbid, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCusaddr, javax.swing.GroupLayout.PREFERRED_SIZE, 667, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 13, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(txtCusid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCusname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTbid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(txtCustel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCuszip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCusaddr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("注意：红色字体处不可修改");

        btnLoad.setText("载入");
        btnLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadActionPerformed(evt);
            }
        });

        btnAdd.setText("新增");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnDelete.setText("删除");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnSave.setText("修改/保存");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnCancel.setText("取消");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnClose.setText("退出");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout basicPicPane1Layout = new javax.swing.GroupLayout(basicPicPane1);
        basicPicPane1.setLayout(basicPicPane1Layout);
        basicPicPane1Layout.setHorizontalGroup(
            basicPicPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, basicPicPane1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtCondition, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSearch)
                .addGap(34, 34, 34))
            .addGroup(basicPicPane1Layout.createSequentialGroup()
                .addGroup(basicPicPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(basicPicPane1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLoad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancel)
                        .addGap(27, 27, 27)
                        .addComponent(btnClose))
                    .addGroup(basicPicPane1Layout.createSequentialGroup()
                        .addContainerGap(33, Short.MAX_VALUE)
                        .addGroup(basicPicPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        basicPicPane1Layout.setVerticalGroup(
            basicPicPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(basicPicPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(basicPicPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSearch)
                    .addComponent(txtCondition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(basicPicPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLoad)
                    .addComponent(btnAdd)
                    .addComponent(btnDelete)
                    .addComponent(btnSave)
                    .addComponent(btnCancel)
                    .addComponent(btnClose)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(basicPicPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(basicPicPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 523, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //模糊查询
    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed

        //根据cusname,tbid,cusemail,cusaddr进行模糊查询
        String condition = this.txtCondition.getText().trim();
        List<Customer> list = cusbiz.findByCondition(condition);
            //显示list中的信息
            showOnTable(list);
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
         // 新增买家
        //获取买家信息
        String cusname = this.txtCusname.getText().trim();
        String Tbid = this.txtTbid.getText().trim();  //淘宝昵称
        String custel = this.txtCustel.getText().trim(); //联系电话
        String cuszip = this.txtCuszip.getText().trim();///邮政编码
        String cusaddr= this.txtCusaddr.getText().trim();
        //验证所获数据是否非空
        if(StringUtil.checkLength(cusname) == false){
            JOptionPane.showMessageDialog(this, "姓名不能为空");
            return;
        }
        if(StringUtil.checkLength(Tbid) == false){
            JOptionPane.showMessageDialog(this, "淘宝昵称不能为空");
            return;
        }
        if(StringUtil.checkLength(custel) == false){
            JOptionPane.showMessageDialog(this, "联系电话不能为空");
            return;
        }
        if(StringUtil.checkLength(cuszip) == false){
            JOptionPane.showMessageDialog(this, "邮政编码不能为空");
            return;
        }
        if(StringUtil.checkLength(cusaddr) == false){
            JOptionPane.showMessageDialog(this, "送货地址不能为空");
            return;
        }
       
        
        //组合对象
        Customer c = new Customer(null,cusname,Tbid,custel,cuszip,cusaddr);
        //调用业务类
        boolean result = cusbiz.add(c);
        if(result == true){
            JOptionPane.showMessageDialog(this, "添加成功");
             List<Customer> list = cusbiz.findAll();
            //显示list的信息
            showOnTable(list);
        }
        else
            JOptionPane.showMessageDialog(this, "添加失败");
        //清孔面板信息
        clearInput();
    }//GEN-LAST:event_btnAddActionPerformed

    //鼠标点击选中表的某一行
    private void tblCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCustomerMouseClicked
        // 鼠标选中某行，该行信息显示到输入面板
        int row = this.tblCustomer.getSelectedRow();//表示被选中的那一行
        //获取每一列的值
        this.txtCusid.setText(this.tblCustomer.getValueAt(row, 0)+"");
        this.txtCusname.setText(this.tblCustomer.getValueAt(row, 1)+"");
        this.txtTbid.setText(this.tblCustomer.getValueAt(row, 2)+"");
        this.txtCustel.setText(this.tblCustomer.getValueAt(row, 3)+"");
        this.txtCuszip.setText(this.tblCustomer.getValueAt(row, 4)+"");
        this.txtCusaddr.setText(this.tblCustomer.getValueAt(row, 5)+"");
        //保存  删除按钮可用
        this.btnSave.setEnabled(true);
        this.btnDelete.setEnabled(true);
    }//GEN-LAST:event_tblCustomerMouseClicked

    //修改/保存按钮
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // 修改买家信息
        //获取买家信息
        int cusid = Integer.parseInt(this.txtCusid.getText().trim());
        String cusname = this.txtCusname.getText().trim();
        String Tbid = this.txtTbid.getText().trim();  //淘宝昵称
        String custel = this.txtCustel.getText().trim(); //联系电话
        String cuszip = this.txtCuszip.getText().trim();///邮政编码
        String cusaddr= this.txtCusaddr.getText().trim();
        //验证所获数据是否非空
        if(StringUtil.checkLength(cusname) == false){
            JOptionPane.showMessageDialog(this, "姓名不能为空");
            return;
        }
        if(StringUtil.checkLength(Tbid) == false){
            JOptionPane.showMessageDialog(this, "淘宝昵称不能为空");
            return;
        }
        if(StringUtil.checkLength(custel) == false){
            JOptionPane.showMessageDialog(this, "联系电话不能为空");
            return;
        }
        if(StringUtil.checkLength(cuszip) == false){
            JOptionPane.showMessageDialog(this, "邮政编码不能为空");
            return;
        }
        if(StringUtil.checkLength(cusaddr) == false){
            JOptionPane.showMessageDialog(this, "送货地址不能为空");
            return;
        }
       
        //组合对象
        Customer c = new Customer(cusid,cusname,Tbid,custel,cuszip,cusaddr);
        //调用业务类
        boolean result = cusbiz.update(c);
        if(result == true){
            JOptionPane.showMessageDialog(this, "修改成功");
             List<Customer> list = cusbiz.findAll();
            //显示list的信息
            showOnTable(list);
        }
        else
            JOptionPane.showMessageDialog(this, "修改失败");
        //清孔面板信息
        clearInput();
    }//GEN-LAST:event_btnSaveActionPerformed

    //删除按钮
    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // 删除买家信息
        int answer = JOptionPane.showConfirmDialog(this, "你确定要删除吗？");
        if(answer == JOptionPane.YES_OPTION){
        //获取cusid
        int cusid = Integer.parseInt(this.txtCusid.getText());
        boolean result = cusbiz.delete(cusid);
        if(result == true){
            JOptionPane.showMessageDialog(this, "删除成功");
            List<Customer> list = cusbiz.findAll();
            //显示list中的信息
            showOnTable(list);
        } else{
            JOptionPane.showMessageDialog(this, "删除失败");

        }
        clearInput();
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    //取消按钮
    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // 界面恢复到最初状态
        clearInput();
        this.btnSave.setEnabled(false);
        this.btnDelete.setEnabled(false);
    }//GEN-LAST:event_btnCancelActionPerformed

    //退出按钮
    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    //载入按钮
    private void btnLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadActionPerformed
        //查询数据库，将数据显示到表格上
        List<Customer> list = cusbiz.findAll();
        //显示list的信息
        showOnTable(list);
    }//GEN-LAST:event_btnLoadActionPerformed
    
    //将制定的list数据显示到表上
    public void showOnTable(List<Customer> list){
        //将制定的list数据显示到表上
        //1.获取指定表格（tblProduct）模型
        DefaultTableModel dtm = (DefaultTableModel) this.tblCustomer.getModel();
        //2.清空表格信息
        while(dtm.getRowCount() > 0){
            dtm.removeRow(0);
        }
        //3.显示表格
        for(Customer c : list){
            Vector vt = new Vector();
            vt.add(c.getCusid());
            vt.add(c.getCusname());
            vt.add(c.getTbid());  //淘宝昵称
            vt.add(c.getCustel());
            vt.add(c.getCusemail()); //邮编
            vt.add(c.getCusaddr());
            dtm.addRow(vt);
        }
    }
    
    //清空面板上的数据
    private void clearInput() {
        this.txtCusid.setText("");
        this.txtCusname.setText("");
        this.txtTbid.setText("");
        this.txtCustel.setText("");
        this.txtCuszip.setText(""); //邮编
        this.txtCusaddr.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.ouc.cpss.view.BasicPicPane basicPicPane1;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnLoad;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCustomer;
    private javax.swing.JTextField txtCondition;
    private javax.swing.JTextField txtCusaddr;
    private javax.swing.JTextField txtCusid;
    private javax.swing.JTextField txtCusname;
    private javax.swing.JTextField txtCustel;
    private javax.swing.JTextField txtCuszip;
    private javax.swing.JTextField txtTbid;
    // End of variables declaration//GEN-END:variables
}
